"""'fix'

Revision ID: 9bfd59eac288
Revises: 102e9f7e3d12
Create Date: 2023-06-21 19:20:44.166318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfd59eac288'
down_revision = '102e9f7e3d12'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('salary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'salary')
    # ### end Alembic commands ###
